### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by hannes7g** [derekantrican/Winforms-Calendar#12]
Is it possible for you to consider changing the license to MIT License please? Thank you

**Comment by derekantrican** [comment]
I'm not the original author of the code by any means, just trying to be a _bit_ more active of a maintainer (but I am very busy).

The original repo at https://www.codeproject.com/Articles/38699/A-Professional-Calendar-Agenda-View-That-You-Will has the LGPL3 license so I've used that. If the main author says otherwise, then I'll change it, but I have no rights to change it on my own accord (since I have contributed approximately 0% to this codebase)
